MERGE INTO Pais (id,codigo,nombre) VALUES(1, 'AF', 'Afganistán');
MERGE INTO Pais (id,codigo,nombre) VALUES(2, 'AX', 'Islas Gland');
MERGE INTO Pais (id,codigo,nombre) VALUES(3, 'AL', 'Albania');
MERGE INTO Pais (id,codigo,nombre) VALUES(4, 'DE', 'Alemania');
MERGE INTO Pais (id,codigo,nombre) VALUES(5, 'AD', 'Andorra');
MERGE INTO Pais (id,codigo,nombre) VALUES(6, 'AO', 'Angola');
MERGE INTO Pais (id,codigo,nombre) VALUES(7, 'AI', 'Anguilla');
MERGE INTO Pais (id,codigo,nombre) VALUES(8, 'AQ', 'Antártida');
MERGE INTO Pais (id,codigo,nombre) VALUES(9, 'AG', 'Antigua y Barbuda');
MERGE INTO Pais (id,codigo,nombre) VALUES(10, 'AN', 'Antillas Holandesas');
MERGE INTO Pais (id,codigo,nombre) VALUES(11, 'SA', 'Arabia Saudí');
MERGE INTO Pais (id,codigo,nombre) VALUES(12, 'DZ', 'Argelia');
MERGE INTO Pais (id,codigo,nombre) VALUES(13, 'AR', 'Argentina');
MERGE INTO Pais (id,codigo,nombre) VALUES(14, 'AM', 'Armenia');
MERGE INTO Pais (id,codigo,nombre) VALUES(15, 'AW', 'Aruba');
MERGE INTO Pais (id,codigo,nombre) VALUES(16, 'AU', 'Australia');
MERGE INTO Pais (id,codigo,nombre) VALUES(17, 'AT', 'Austria');
MERGE INTO Pais (id,codigo,nombre) VALUES(18, 'AZ', 'Azerbaiyán');
MERGE INTO Pais (id,codigo,nombre) VALUES(19, 'BS', 'Bahamas');
MERGE INTO Pais (id,codigo,nombre) VALUES(20, 'BH', 'Bahréin');
MERGE INTO Pais (id,codigo,nombre) VALUES(21, 'BD', 'Bangladesh');
MERGE INTO Pais (id,codigo,nombre) VALUES(22, 'BB', 'Barbados');
MERGE INTO Pais (id,codigo,nombre) VALUES(23, 'BY', 'Bielorrusia');
MERGE INTO Pais (id,codigo,nombre) VALUES(24, 'BE', 'Bélgica');
MERGE INTO Pais (id,codigo,nombre) VALUES(25, 'BZ', 'Belice');
MERGE INTO Pais (id,codigo,nombre) VALUES(26, 'BJ', 'Benin');
MERGE INTO Pais (id,codigo,nombre) VALUES(27, 'BM', 'Bermudas');
MERGE INTO Pais (id,codigo,nombre) VALUES(28, 'BT', 'Bhután');
MERGE INTO Pais (id,codigo,nombre) VALUES(29, 'BO', 'Bolivia');
MERGE INTO Pais (id,codigo,nombre) VALUES(30, 'BA', 'Bosnia y Herzegovina');
MERGE INTO Pais (id,codigo,nombre) VALUES(31, 'BW', 'Botsuana');
MERGE INTO Pais (id,codigo,nombre) VALUES(32, 'BV', 'Isla Bouvet');
MERGE INTO Pais (id,codigo,nombre) VALUES(33, 'BR', 'Brasil');
MERGE INTO Pais (id,codigo,nombre) VALUES(34, 'BN', 'Brunéi');
MERGE INTO Pais (id,codigo,nombre) VALUES(35, 'BG', 'Bulgaria');
MERGE INTO Pais (id,codigo,nombre) VALUES(36, 'BF', 'Burkina Faso');
MERGE INTO Pais (id,codigo,nombre) VALUES(37, 'BI', 'Burundi');
MERGE INTO Pais (id,codigo,nombre) VALUES(38, 'CV', 'Cabo Verde');
MERGE INTO Pais (id,codigo,nombre) VALUES(39, 'KY', 'Islas Caimán');
MERGE INTO Pais (id,codigo,nombre) VALUES(40, 'KH', 'Camboya');
MERGE INTO Pais (id,codigo,nombre) VALUES(41, 'CM', 'Camerún');
MERGE INTO Pais (id,codigo,nombre) VALUES(42, 'CA', 'Canadá');
MERGE INTO Pais (id,codigo,nombre) VALUES(43, 'CF', 'República Centroafricana');
MERGE INTO Pais (id,codigo,nombre) VALUES(44, 'TD', 'Chad');
MERGE INTO Pais (id,codigo,nombre) VALUES(45, 'CZ', 'República Checa');
MERGE INTO Pais (id,codigo,nombre) VALUES(46, 'CL', 'Chile');
MERGE INTO Pais (id,codigo,nombre) VALUES(47, 'CN', 'China');
MERGE INTO Pais (id,codigo,nombre) VALUES(48, 'CY', 'Chipre');
MERGE INTO Pais (id,codigo,nombre) VALUES(49, 'CX', 'Isla de Navidad');
MERGE INTO Pais (id,codigo,nombre) VALUES(50, 'VA', 'Ciudad del Vaticano');
MERGE INTO Pais (id,codigo,nombre) VALUES(51, 'CC', 'Islas Cocos');
MERGE INTO Pais (id,codigo,nombre) VALUES(52, 'CO', 'Colombia');
MERGE INTO Pais (id,codigo,nombre) VALUES(53, 'KM', 'Comoras');
MERGE INTO Pais (id,codigo,nombre) VALUES(54, 'CD', 'República Democrática del Congo');
MERGE INTO Pais (id,codigo,nombre) VALUES(55, 'CG', 'Congo');
MERGE INTO Pais (id,codigo,nombre) VALUES(56, 'CK', 'Islas Cook');
MERGE INTO Pais (id,codigo,nombre) VALUES(57, 'KP', 'Corea del Norte');
MERGE INTO Pais (id,codigo,nombre) VALUES(58, 'KR', 'Corea del Sur');
MERGE INTO Pais (id,codigo,nombre) VALUES(59, 'CI', 'Costa de Marfil');
MERGE INTO Pais (id,codigo,nombre) VALUES(60, 'CR', 'Costa Rica');
MERGE INTO Pais (id,codigo,nombre) VALUES(61, 'HR', 'Croacia');
MERGE INTO Pais (id,codigo,nombre) VALUES(62, 'CU', 'Cuba');
MERGE INTO Pais (id,codigo,nombre) VALUES(63, 'DK', 'Dinamarca');
MERGE INTO Pais (id,codigo,nombre) VALUES(64, 'DM', 'Dominica');
MERGE INTO Pais (id,codigo,nombre) VALUES(65, 'DO', 'República Dominicana');
MERGE INTO Pais (id,codigo,nombre) VALUES(66, 'EC', 'Ecuador');
MERGE INTO Pais (id,codigo,nombre) VALUES(67, 'EG', 'Egipto');
MERGE INTO Pais (id,codigo,nombre) VALUES(68, 'SV', 'El Salvador');
MERGE INTO Pais (id,codigo,nombre) VALUES(69, 'AE', 'Emiratos Árabes Unidos');
MERGE INTO Pais (id,codigo,nombre) VALUES(70, 'ER', 'Eritrea');
MERGE INTO Pais (id,codigo,nombre) VALUES(71, 'SK', 'Eslovaquia');
MERGE INTO Pais (id,codigo,nombre) VALUES(72, 'SI', 'Eslovenia');
MERGE INTO Pais (id,codigo,nombre) VALUES(73, 'ES', 'España');
MERGE INTO Pais (id,codigo,nombre) VALUES(74, 'UM', 'Islas ultramarinas de Estados Unidos');
MERGE INTO Pais (id,codigo,nombre) VALUES(75, 'US', 'Estados Unidos');
MERGE INTO Pais (id,codigo,nombre) VALUES(76, 'EE', 'Estonia');
MERGE INTO Pais (id,codigo,nombre) VALUES(77, 'ET', 'Etiopía');
MERGE INTO Pais (id,codigo,nombre) VALUES(78, 'FO', 'Islas Feroe');
MERGE INTO Pais (id,codigo,nombre) VALUES(79, 'PH', 'Filipinas');
MERGE INTO Pais (id,codigo,nombre) VALUES(80, 'FI', 'Finlandia');
MERGE INTO Pais (id,codigo,nombre) VALUES(81, 'FJ', 'Fiyi');
MERGE INTO Pais (id,codigo,nombre) VALUES(82, 'FR', 'Francia');
MERGE INTO Pais (id,codigo,nombre) VALUES(83, 'GA', 'Gabón');
MERGE INTO Pais (id,codigo,nombre) VALUES(84, 'GM', 'Gambia');
MERGE INTO Pais (id,codigo,nombre) VALUES(85, 'GE', 'Georgia');
MERGE INTO Pais (id,codigo,nombre) VALUES(86, 'GS', 'Islas Georgias del Sur y Sandwich del Sur');
MERGE INTO Pais (id,codigo,nombre) VALUES(87, 'GH', 'Ghana');
MERGE INTO Pais (id,codigo,nombre) VALUES(88, 'GI', 'Gibraltar');
MERGE INTO Pais (id,codigo,nombre) VALUES(89, 'GD', 'Granada');
MERGE INTO Pais (id,codigo,nombre) VALUES(90, 'GR', 'Grecia');
MERGE INTO Pais (id,codigo,nombre) VALUES(91, 'GL', 'Groenlandia');
MERGE INTO Pais (id,codigo,nombre) VALUES(92, 'GP', 'Guadalupe');
MERGE INTO Pais (id,codigo,nombre) VALUES(93, 'GU', 'Guam');
MERGE INTO Pais (id,codigo,nombre) VALUES(94, 'GT', 'Guatemala');
MERGE INTO Pais (id,codigo,nombre) VALUES(95, 'GF', 'Guayana Francesa');
MERGE INTO Pais (id,codigo,nombre) VALUES(96, 'GN', 'Guinea');
MERGE INTO Pais (id,codigo,nombre) VALUES(97, 'GQ', 'Guinea Ecuatorial');
MERGE INTO Pais (id,codigo,nombre) VALUES(98, 'GW', 'Guinea-Bissau');
MERGE INTO Pais (id,codigo,nombre) VALUES(99, 'GY', 'Guyana');
MERGE INTO Pais (id,codigo,nombre) VALUES(100, 'HT', 'Haití');
MERGE INTO Pais (id,codigo,nombre) VALUES(101, 'HM', 'Islas Heard y McDonald');
MERGE INTO Pais (id,codigo,nombre) VALUES(102, 'HN', 'Honduras');
MERGE INTO Pais (id,codigo,nombre) VALUES(103, 'HK', 'Hong Kong');
MERGE INTO Pais (id,codigo,nombre) VALUES(104, 'HU', 'Hungría');
MERGE INTO Pais (id,codigo,nombre) VALUES(105, 'IN', 'India');
MERGE INTO Pais (id,codigo,nombre) VALUES(106, 'ID', 'Indonesia');
MERGE INTO Pais (id,codigo,nombre) VALUES(107, 'IR', 'Irán');
MERGE INTO Pais (id,codigo,nombre) VALUES(108, 'IQ', 'Iraq');
MERGE INTO Pais (id,codigo,nombre) VALUES(109, 'IE', 'Irlanda');
MERGE INTO Pais (id,codigo,nombre) VALUES(110, 'IS', 'Islandia');
MERGE INTO Pais (id,codigo,nombre) VALUES(111, 'IL', 'Israel');
MERGE INTO Pais (id,codigo,nombre) VALUES(112, 'IT', 'Italia');
MERGE INTO Pais (id,codigo,nombre) VALUES(113, 'JM', 'Jamaica');
MERGE INTO Pais (id,codigo,nombre) VALUES(114, 'JP', 'Japón');
MERGE INTO Pais (id,codigo,nombre) VALUES(115, 'JO', 'Jordania');
MERGE INTO Pais (id,codigo,nombre) VALUES(116, 'KZ', 'Kazajstán');
MERGE INTO Pais (id,codigo,nombre) VALUES(117, 'KE', 'Kenia');
MERGE INTO Pais (id,codigo,nombre) VALUES(118, 'KG', 'Kirguistán');
MERGE INTO Pais (id,codigo,nombre) VALUES(119, 'KI', 'Kiribati');
MERGE INTO Pais (id,codigo,nombre) VALUES(120, 'KW', 'Kuwait');
MERGE INTO Pais (id,codigo,nombre) VALUES(121, 'LA', 'Laos');
MERGE INTO Pais (id,codigo,nombre) VALUES(122, 'LS', 'Lesotho');
MERGE INTO Pais (id,codigo,nombre) VALUES(123, 'LV', 'Letonia');
MERGE INTO Pais (id,codigo,nombre) VALUES(124, 'LB', 'Líbano');
MERGE INTO Pais (id,codigo,nombre) VALUES(125, 'LR', 'Liberia');
MERGE INTO Pais (id,codigo,nombre) VALUES(126, 'LY', 'Libia');
MERGE INTO Pais (id,codigo,nombre) VALUES(127, 'LI', 'Liechtenstein');
MERGE INTO Pais (id,codigo,nombre) VALUES(128, 'LT', 'Lituania');
MERGE INTO Pais (id,codigo,nombre) VALUES(129, 'LU', 'Luxemburgo');
MERGE INTO Pais (id,codigo,nombre) VALUES(130, 'MO', 'Macao');
MERGE INTO Pais (id,codigo,nombre) VALUES(131, 'MK', 'ARY Macedonia');
MERGE INTO Pais (id,codigo,nombre) VALUES(132, 'MG', 'Madagascar');
MERGE INTO Pais (id,codigo,nombre) VALUES(133, 'MY', 'Malasia');
MERGE INTO Pais (id,codigo,nombre) VALUES(134, 'MW', 'Malawi');
MERGE INTO Pais (id,codigo,nombre) VALUES(135, 'MV', 'Maldivas');
MERGE INTO Pais (id,codigo,nombre) VALUES(136, 'ML', 'Malí');
MERGE INTO Pais (id,codigo,nombre) VALUES(137, 'MT', 'Malta');
MERGE INTO Pais (id,codigo,nombre) VALUES(138, 'FK', 'Islas Malvinas');
MERGE INTO Pais (id,codigo,nombre) VALUES(139, 'MP', 'Islas Marianas del Norte');
MERGE INTO Pais (id,codigo,nombre) VALUES(140, 'MA', 'Marruecos');
MERGE INTO Pais (id,codigo,nombre) VALUES(141, 'MH', 'Islas Marshall');
MERGE INTO Pais (id,codigo,nombre) VALUES(142, 'MQ', 'Martinica');
MERGE INTO Pais (id,codigo,nombre) VALUES(143, 'MU', 'Mauricio');
MERGE INTO Pais (id,codigo,nombre) VALUES(144, 'MR', 'Mauritania');
MERGE INTO Pais (id,codigo,nombre) VALUES(145, 'YT', 'Mayotte');
MERGE INTO Pais (id,codigo,nombre) VALUES(146, 'MX', 'México');
MERGE INTO Pais (id,codigo,nombre) VALUES(147, 'FM', 'Micronesia');
MERGE INTO Pais (id,codigo,nombre) VALUES(148, 'MD', 'Moldavia');
MERGE INTO Pais (id,codigo,nombre) VALUES(149, 'MC', 'Mónaco');
MERGE INTO Pais (id,codigo,nombre) VALUES(150, 'MN', 'Mongolia');
MERGE INTO Pais (id,codigo,nombre) VALUES(151, 'MS', 'Montserrat');
MERGE INTO Pais (id,codigo,nombre) VALUES(152, 'MZ', 'Mozambique');
MERGE INTO Pais (id,codigo,nombre) VALUES(153, 'MM', 'Myanmar');
MERGE INTO Pais (id,codigo,nombre) VALUES(154, 'NA', 'Namibia');
MERGE INTO Pais (id,codigo,nombre) VALUES(155, 'NR', 'Nauru');
MERGE INTO Pais (id,codigo,nombre) VALUES(156, 'NP', 'Nepal');
MERGE INTO Pais (id,codigo,nombre) VALUES(157, 'NI', 'Nicaragua');
MERGE INTO Pais (id,codigo,nombre) VALUES(158, 'NE', 'Níger');
MERGE INTO Pais (id,codigo,nombre) VALUES(159, 'NG', 'Nigeria');
MERGE INTO Pais (id,codigo,nombre) VALUES(160, 'NU', 'Niue');
MERGE INTO Pais (id,codigo,nombre) VALUES(161, 'NF', 'Isla Norfolk');
MERGE INTO Pais (id,codigo,nombre) VALUES(162, 'NO', 'Noruega');
MERGE INTO Pais (id,codigo,nombre) VALUES(163, 'NC', 'Nueva Caledonia');
MERGE INTO Pais (id,codigo,nombre) VALUES(164, 'NZ', 'Nueva Zelanda');
MERGE INTO Pais (id,codigo,nombre) VALUES(165, 'OM', 'Omán');
MERGE INTO Pais (id,codigo,nombre) VALUES(166, 'NL', 'Países Bajos');
MERGE INTO Pais (id,codigo,nombre) VALUES(167, 'PK', 'Pakistán');
MERGE INTO Pais (id,codigo,nombre) VALUES(168, 'PW', 'Palau');
MERGE INTO Pais (id,codigo,nombre) VALUES(169, 'PS', 'Palestina');
MERGE INTO Pais (id,codigo,nombre) VALUES(170, 'PA', 'Panamá');
MERGE INTO Pais (id,codigo,nombre) VALUES(171, 'PG', 'Papúa Nueva Guinea');
MERGE INTO Pais (id,codigo,nombre) VALUES(172, 'PY', 'Paraguay');
MERGE INTO Pais (id,codigo,nombre) VALUES(173, 'PE', 'Perú');
MERGE INTO Pais (id,codigo,nombre) VALUES(174, 'PN', 'Islas Pitcairn');
MERGE INTO Pais (id,codigo,nombre) VALUES(175, 'PF', 'Polinesia Francesa');
MERGE INTO Pais (id,codigo,nombre) VALUES(176, 'PL', 'Polonia');
MERGE INTO Pais (id,codigo,nombre) VALUES(177, 'PT', 'Portugal');
MERGE INTO Pais (id,codigo,nombre) VALUES(178, 'PR', 'Puerto Rico');
MERGE INTO Pais (id,codigo,nombre) VALUES(179, 'QA', 'Qatar');
MERGE INTO Pais (id,codigo,nombre) VALUES(180, 'GB', 'Reino Unido');
MERGE INTO Pais (id,codigo,nombre) VALUES(181, 'RE', 'Reunión');
MERGE INTO Pais (id,codigo,nombre) VALUES(182, 'RW', 'Ruanda');
MERGE INTO Pais (id,codigo,nombre) VALUES(183, 'RO', 'Rumania');
MERGE INTO Pais (id,codigo,nombre) VALUES(184, 'RU', 'Rusia');
MERGE INTO Pais (id,codigo,nombre) VALUES(185, 'EH', 'Sahara Occidental');
MERGE INTO Pais (id,codigo,nombre) VALUES(186, 'SB', 'Islas Salomón');
MERGE INTO Pais (id,codigo,nombre) VALUES(187, 'WS', 'Samoa');
MERGE INTO Pais (id,codigo,nombre) VALUES(188, 'AS', 'Samoa Americana');
MERGE INTO Pais (id,codigo,nombre) VALUES(189, 'KN', 'San Cristóbal y Nevis');
MERGE INTO Pais (id,codigo,nombre) VALUES(190, 'SM', 'San Marino');
MERGE INTO Pais (id,codigo,nombre) VALUES(191, 'PM', 'San Pedro y Miquelón');
MERGE INTO Pais (id,codigo,nombre) VALUES(192, 'VC', 'San Vicente y las Granadinas');
MERGE INTO Pais (id,codigo,nombre) VALUES(193, 'SH', 'Santa Helena');
MERGE INTO Pais (id,codigo,nombre) VALUES(194, 'LC', 'Santa Lucía');
MERGE INTO Pais (id,codigo,nombre) VALUES(195, 'ST', 'Santo Tomé y Príncipe');
MERGE INTO Pais (id,codigo,nombre) VALUES(196, 'SN', 'Senegal');
MERGE INTO Pais (id,codigo,nombre) VALUES(197, 'CS', 'Serbia y Montenegro');
MERGE INTO Pais (id,codigo,nombre) VALUES(198, 'SC', 'Seychelles');
MERGE INTO Pais (id,codigo,nombre) VALUES(199, 'SL', 'Sierra Leona');
MERGE INTO Pais (id,codigo,nombre) VALUES(200, 'SG', 'Singapur');
MERGE INTO Pais (id,codigo,nombre) VALUES(201, 'SY', 'Siria');
MERGE INTO Pais (id,codigo,nombre) VALUES(202, 'SO', 'Somalia');
MERGE INTO Pais (id,codigo,nombre) VALUES(203, 'LK', 'Sri Lanka');
MERGE INTO Pais (id,codigo,nombre) VALUES(204, 'SZ', 'Suazilandia');
MERGE INTO Pais (id,codigo,nombre) VALUES(205, 'ZA', 'Sudáfrica');
MERGE INTO Pais (id,codigo,nombre) VALUES(206, 'SD', 'Sudán');
MERGE INTO Pais (id,codigo,nombre) VALUES(207, 'SE', 'Suecia');
MERGE INTO Pais (id,codigo,nombre) VALUES(208, 'CH', 'Suiza');
MERGE INTO Pais (id,codigo,nombre) VALUES(209, 'SR', 'Surinam');
MERGE INTO Pais (id,codigo,nombre) VALUES(210, 'SJ', 'Svalbard y Jan Mayen');
MERGE INTO Pais (id,codigo,nombre) VALUES(211, 'TH', 'Tailandia');
MERGE INTO Pais (id,codigo,nombre) VALUES(212, 'TW', 'Taiwán');
MERGE INTO Pais (id,codigo,nombre) VALUES(213, 'TZ', 'Tanzania');
MERGE INTO Pais (id,codigo,nombre) VALUES(214, 'TJ', 'Tayikistán');
MERGE INTO Pais (id,codigo,nombre) VALUES(215, 'IO', 'Territorio Británico del Océano Índico');
MERGE INTO Pais (id,codigo,nombre) VALUES(216, 'TF', 'Territorios Australes Franceses');
MERGE INTO Pais (id,codigo,nombre) VALUES(217, 'TL', 'Timor Oriental');
MERGE INTO Pais (id,codigo,nombre) VALUES(218, 'TG', 'Togo');
MERGE INTO Pais (id,codigo,nombre) VALUES(219, 'TK', 'Tokelau');
MERGE INTO Pais (id,codigo,nombre) VALUES(220, 'TO', 'Tonga');
MERGE INTO Pais (id,codigo,nombre) VALUES(221, 'TT', 'Trinidad y Tobago');
MERGE INTO Pais (id,codigo,nombre) VALUES(222, 'TN', 'Túnez');
MERGE INTO Pais (id,codigo,nombre) VALUES(223, 'TC', 'Islas Turcas y Caicos');
MERGE INTO Pais (id,codigo,nombre) VALUES(224, 'TM', 'Turkmenistán');
MERGE INTO Pais (id,codigo,nombre) VALUES(225, 'TR', 'Turquía');
MERGE INTO Pais (id,codigo,nombre) VALUES(226, 'TV', 'Tuvalu');
MERGE INTO Pais (id,codigo,nombre) VALUES(227, 'UA', 'Ucrania');
MERGE INTO Pais (id,codigo,nombre) VALUES(228, 'UG', 'Uganda');
MERGE INTO Pais (id,codigo,nombre) VALUES(229, 'UY', 'Uruguay');
MERGE INTO Pais (id,codigo,nombre) VALUES(230, 'UZ', 'Uzbekistán');
MERGE INTO Pais (id,codigo,nombre) VALUES(231, 'VU', 'Vanuatu');
MERGE INTO Pais (id,codigo,nombre) VALUES(232, 'VE', 'Venezuela');
MERGE INTO Pais (id,codigo,nombre) VALUES(233, 'VN', 'Vietnam');
MERGE INTO Pais (id,codigo,nombre) VALUES(234, 'VG', 'Islas Vírgenes Británicas');
MERGE INTO Pais (id,codigo,nombre) VALUES(235, 'VI', 'Islas Vírgenes de los Estados Unidos');
MERGE INTO Pais (id,codigo,nombre) VALUES(236, 'WF', 'Wallis y Futuna');
MERGE INTO Pais (id,codigo,nombre) VALUES(237, 'YE', 'Yemen');
MERGE INTO Pais (id,codigo,nombre) VALUES(238, 'DJ', 'Yibuti');
MERGE INTO Pais (id,codigo,nombre) VALUES(239, 'ZM', 'Zambia');
MERGE INTO Pais (id,codigo,nombre) VALUES(240, 'ZW', 'Zimbabue');